import Link from "next/link";

export const metadata = {
  title: "How to Source Fabric Wholesale from Surat",
  description: "A practical guide to wholesale fabric sourcing from Surat: specifications, sampling, quantities, quality checks and supplier communication.",
  alternates: { canonical: "/guides/how-to-source-fabric-wholesale-from-surat" },
};

export default function Page() {
  return <main><section className="pageHero"><div className="container"><p className="eyebrow">Buyer guide · Surat textiles</p><h1>How to source fabric wholesale from Surat.</h1><p className="lead">Successful wholesale sourcing starts with a clear specification, a sample-led quality check and direct communication about quantity and delivery requirements.</p></div></section><section className="section"><div className="container prose"><h2>1. Start with the specification</h2><p className="lead">Describe the fabric by its trade name or construction, intended use, required width, GSM, colour, finish and print or dye route where relevant. Trade names can vary between suppliers, so the physical quality and specification should be confirmed before a bulk commitment.</p><h2>2. Request a sample</h2><p className="lead">A sample lets your team assess hand feel, drape, surface, opacity, colour and suitability for cutting and stitching. For repeat production, keep an approved reference sample and communicate any permitted tolerances.</p><h2>3. Discuss quantity and commercial requirements</h2><p className="lead">Ask about available quantity, minimum order expectations, packing, dispatch timing and whether the quality is ready stock, RFD, dyed or developed to order. Confirm commercial terms directly with the supplier.</p><h2>4. Check lot-specific details</h2><p className="lead">GSM, finished width, composition, construction and finish can vary by quality and lot. Treat catalogue information as a starting point and confirm the exact production specification for the material you are buying.</p><h2>5. Keep the enquiry precise</h2><p className="lead">A concise enquiry helps a supplier respond quickly. Include fabric name, intended use, approximate quantity, required width or GSM if known, colour or print requirement, destination and target timeline.</p><p className="lead">Moksha Fabrics can discuss textile sourcing requirements from Surat across listed dress-material, printed, dyed, synthetic/blended and related fabric categories.</p><div className="actions"><Link className="button buttonDark" href="/contact">Send a sourcing enquiry</Link><Link className="textLink" href="/fabrics">Browse fabrics</Link></div></div></section></main>;
}
