export type Fabric = {
  slug: string;
  name: string;
  category: string;
  categorySlug: string;
  description: string;
  application: string;
  specifications: string[];
  status: "Indicative specification" | "Catalogue category";
  imageUrl?: string;
  imageAlt?: string;
};

// Market-informed specifications are indicative only. Confirm exact GSM, width,
// composition, construction and finish with Moksha Fabrics before publishing as a lot-specific spec.
// imageUrl values are temporary reference/demo imagery and should be replaced with Moksha Fabrics photography.
export const fabrics: Fabric[] = [
  { slug: "bsy-12kg", name: "BSY 12KG", category: "Dress Material Fabrics", categorySlug: "dress-material-fabrics", description: "Commercial dress-material fabric quality supplied under the BSY 12KG trade name.", application: "Dress materials, suits, coordinated sets and women's fashion garments.", specifications: ["Approx. 12 kg trade quality", "Width: confirm by lot", "Composition: confirm by lot", "Bulk sourcing"], status: "Indicative specification", imageUrl: "https://www.textilium.com/cdn/shop/files/shutterstock_1595272699_CROPPED_v1.jpg?v=1689619669&width=2000", imageAlt: "Blue textile rolls used as temporary catalogue reference imagery" },
  { slug: "leyon-8kg", name: "Leyon 8KG", category: "Dyed / RFD Fabrics", categorySlug: "dyed-fabrics", description: "Leyon 8KG trade quality available in dyed and RFD development routes.", application: "Dress materials, kurtis, dresses and fashion garments.", specifications: ["Approx. 8 kg trade quality", "Dyed / RFD", "Width: confirm by lot", "Composition: confirm by lot"], status: "Indicative specification", imageUrl: "https://www.averbforkeepingwarm.com/cdn/shop/files/BUAISOU-7334.jpg?v=1713023577&width=1887", imageAlt: "Indigo-dyed fabric roll used as temporary catalogue reference imagery" },
  { slug: "rayon", name: "Rayon", category: "Rayon Fabrics", categorySlug: "dress-material-fabrics", description: "Soft, fluid rayon fabric suited to comfortable fashion garments and dress-material applications.", application: "Kurtis, dresses, tops, palazzos, ethnicwear and dress materials.", specifications: ["Cellulosic rayon / viscose family", "Soft drape and breathable hand", "Width and GSM: confirm by lot", "Dyed / printed options subject to availability"], status: "Indicative specification", imageUrl: "https://cdn.salla.sa/WqrAj/da9d67ba-679b-4ac6-8352-695202ac65f3-1000x750-X2iwQ8EPSp4GBB6bKFAiGJkRHVMr74HC5TQ5D6Pv.jpg", imageAlt: "Lavender rayon fabric roll used as temporary catalogue reference imagery" },
  { slug: "camric", name: "Camric / Cambric", category: "Cotton Fabrics", categorySlug: "dress-material-fabrics", description: "Fine, closely woven cambric-type fabric with a smooth surface and clean finish.", application: "Kurtis, summer garments, printed dress materials, linings and lightweight apparel.", specifications: ["Typically plain weave", "Commonly cotton; blend may vary", "Indicative GSM: approx. 60–140 GSM depending on quality", "Dyed / printed"], status: "Indicative specification", imageUrl: "https://webmerx.sgp1.cdn.digitaloceanspaces.com/tailoringindia/product_images/1647063689.1-.jpg", imageAlt: "White cotton cambric fabric used as temporary catalogue reference imagery" },
  { slug: "star-georgette", name: "Star Georgette", category: "Georgette Fabrics", categorySlug: "dress-material-fabrics", description: "Lightweight georgette quality available in dyed and RFD routes for flowing fashion garments.", application: "Dresses, kurtis, sarees, dupattas and women's fashion garments.", specifications: ["Georgette construction", "Dyed / RFD", "Lightweight flowing handle", "Width and GSM: confirm by lot"], status: "Indicative specification", imageUrl: "https://static.fibre2fashion.com/MemberResources/LeadResources/8/2023/10/Buyer/23216999/Images/23216999_0_georgette.jpg", imageAlt: "Pink georgette fabric close-up used as temporary catalogue reference imagery" },
  { slug: "fandy", name: "Fandy", category: "Dress Material Fabrics", categorySlug: "dress-material-fabrics", description: "Fandy trade quality for dress-material and fashion applications.", application: "Dress materials, kurtis and women's apparel.", specifications: ["Trade quality name", "Width: confirm by lot", "Composition: confirm by lot", "Finish: confirm by lot"], status: "Indicative specification", imageUrl: "https://http2.mlstatic.com/D_NQ_NP_616480-MLM88983866452_082025-O.webp", imageAlt: "Colorful floral fabric roll used as temporary catalogue reference imagery" },
  { slug: "sindoor", name: "Sindoor", category: "Dress Material Fabrics", categorySlug: "dress-material-fabrics", description: "Sindoor trade quality for commercial fashion and dress-material sourcing.", application: "Dress materials, ethnicwear and women's fashion garments.", specifications: ["Trade quality name", "Width: confirm by lot", "Composition: confirm by lot", "Colour / finish: confirm by lot"], status: "Indicative specification", imageUrl: "https://www.textilium.com/cdn/shop/files/shutterstock_1595272699_CROPPED_v1.jpg?v=1689619669&width=2000", imageAlt: "Blue textile rolls used as temporary catalogue reference imagery" },
  { slug: "french-crepe-10kg", name: "French Crepe 10KG", category: "Crepe Fabrics", categorySlug: "synthetic-blended-fabrics", description: "French crepe quality commonly supplied as a polyester RFD base for printing and fashion garments.", application: "Kurtis, dresses, tops, gowns, sarees, dress materials and women's fashionwear.", specifications: ["Polyester RFD base", "Approx. 10 kg trade quality", "Typical width: 44 inches", "Suitable for digital / customized printing"], status: "Indicative specification", imageUrl: "https://img1.paisawapas.com/images/2024/06/17124229/Crepe-Fabric.jpg", imageAlt: "Pink crepe fabric close-up used as temporary catalogue reference imagery" },
  { slug: "black-rangoli-crush", name: "Black Rangoli Crush", category: "Crush / Textured Fabrics", categorySlug: "synthetic-blended-fabrics", description: "Textured crush-style quality listed under the Black Rangoli trade name.", application: "Fashion garments, dress materials and textured apparel.", specifications: ["Crush / textured surface", "Colour: Black trade quality", "Width and GSM: confirm by lot", "Composition: confirm by lot"], status: "Indicative specification", imageUrl: "https://www.textilium.com/cdn/shop/files/shutterstock_1595272699_CROPPED_v1.jpg?v=1689619669&width=2000", imageAlt: "Textile rolls used as temporary catalogue reference imagery for textured fabric" },
  { slug: "kota-checks", name: "Kota Checks", category: "Checks / RFD Fabrics", categorySlug: "dyed-fabrics", description: "Kota Checks RFD fabric with a lightweight check pattern and scope for custom dyeing.", application: "Apparel, dress materials, lightweight garments and creative fashion collections.", specifications: ["RFD / ready-for-dyeing", "Check pattern", "Indicative GSM: approx. 100–200 GSM", "Typical width: approx. 44 inches"], status: "Indicative specification", imageUrl: "https://a.allegroimg.com/original/11c97c/f74db46541d3935f0f97e1b8efda/Tkanina-bawelniana-surowka-100-plotno-ecru-bez-OEKOTEX-140g-m2-160cm-0-5-m", imageAlt: "Natural woven fabric roll used as temporary catalogue reference imagery" },
  { slug: "chocolate", name: "Chocolate", category: "Dress Material Fabrics", categorySlug: "dress-material-fabrics", description: "Chocolate trade quality for commercial dress-material and fashion sourcing.", application: "Dress materials, ethnicwear and women's apparel.", specifications: ["Trade quality name", "Width: confirm by lot", "Composition: confirm by lot", "Finish: confirm by lot"], status: "Indicative specification", imageUrl: "https://images.meine-gardinen.de/item/images/50677/full/50677-Baumwollstoff-Stoff-Dekostoff-uni-orange_3.jpg", imageAlt: "Colorful fabric rolls used as temporary catalogue reference imagery" },
  { slug: "bourban", name: "Bourban", category: "Dress Material Fabrics", categorySlug: "dress-material-fabrics", description: "Bourban trade quality for fashion and dress-material applications.", application: "Women's fashion garments, dress materials and coordinated sets.", specifications: ["Trade quality name", "Width: confirm by lot", "Composition: confirm by lot", "Finish: confirm by lot"], status: "Indicative specification", imageUrl: "https://i.etsystatic.com/54879385/r/il/9a39da/6608921560/il_794xN.6608921560_r3no.jpg", imageAlt: "Rolled rayon fabrics used as temporary catalogue reference imagery" },
  { slug: "printed-fabrics", name: "Printed Fabrics", category: "Printed Fabrics", categorySlug: "printed-fabrics", description: "Printed textile fabrics for fashion, garment and wholesale applications.", application: "Dress materials, garments, ethnicwear and fashion collections.", specifications: ["Print development", "Width to specification", "Bulk sourcing"], status: "Catalogue category", imageUrl: "https://http2.mlstatic.com/D_NQ_NP_616480-MLM88983866452_082025-O.webp", imageAlt: "Floral printed fabric roll used as temporary catalogue reference imagery" },
  { slug: "dress-material-fabrics", name: "Dress Material Fabrics", category: "Dress Material Fabrics", categorySlug: "dress-material-fabrics", description: "Fabric options suited to dress materials, coordinated sets and fashion collections.", application: "Dress materials, suits, coordinated sets and apparel.", specifications: ["Construction to requirement", "Width to specification", "Sampling available on request"], status: "Catalogue category", imageUrl: "https://www.textilium.com/cdn/shop/files/shutterstock_1595272699_CROPPED_v1.jpg?v=1689619669&width=2000", imageAlt: "Textile rolls used as temporary catalogue reference imagery" },
  { slug: "synthetic-blended-fabrics", name: "Synthetic & Blended Fabrics", category: "Synthetic & Blended Fabrics", categorySlug: "synthetic-blended-fabrics", description: "Synthetic and blended constructions for practical fashion and commercial textile applications.", application: "Apparel, fashion collections and commercial garments.", specifications: ["Blend varies by development", "Width to specification", "Bulk sourcing"], status: "Catalogue category", imageUrl: "https://s.alicdn.com/%40sc04/kf/Hdb3f6b5a5f02402181abf308c8dcb30f8/Senfa-Lightweight-Recycled-Polyester-Woven-Printed-Fabric-High-Quality-Japan-Style-Solid-Pattern-Printable-Textiles.jpg", imageAlt: "White polyester fabric roll used as temporary catalogue reference imagery" },
  { slug: "dyed-fabrics", name: "Dyed Fabrics", category: "Dyed Fabrics", categorySlug: "dyed-fabrics", description: "Dyed textile fabrics for buyers looking for colour consistency and flexible sourcing.", application: "Apparel, dress materials and garment production.", specifications: ["Colour development", "Finish to requirement", "Bulk sourcing"], status: "Catalogue category", imageUrl: "https://www.averbforkeepingwarm.com/cdn/shop/files/BUAISOU-7334.jpg?v=1713023577&width=1887", imageAlt: "Indigo-dyed fabric roll used as temporary catalogue reference imagery" },
];

export function getFabric(slug: string) {
  return fabrics.find((fabric) => fabric.slug === slug);
}
